package com.noteflow.study;

import com.noteflow.documents.*;
import com.noteflow.tasks.*;
import com.noteflow.users.DevUserService;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class StudyService {
    private static final Set<String> GRADES=Set.of("AGAIN","HARD","GOOD","EASY");
    private final DevUserService users; private final DocumentRepository documents; private final TaskDispatchService tasks; private final JdbcTemplate jdbc;
    public StudyService(DevUserService u,DocumentRepository d,TaskDispatchService t,JdbcTemplate j){users=u;documents=d;tasks=t;jdbc=j;}

    @Transactional public Map<String,Object> generateDeck(UUID documentId){UUID u=users.currentUserId();Document d=ownedReady(documentId,u);var active=jdbc.queryForList("SELECT id,status FROM flashcard_decks WHERE document_id=? AND user_id=? AND status IN ('GENERATING','PARTIAL') ORDER BY version DESC LIMIT 1",documentId,u);if(!active.isEmpty())return active.get(0);int v=jdbc.queryForObject("SELECT COALESCE(MAX(version),0)+1 FROM flashcard_decks WHERE document_id=?",Integer.class,documentId);UUID id=UUID.randomUUID();jdbc.update("INSERT INTO flashcard_decks(id,document_id,user_id,version,title,status) VALUES (?,?,?,?,?,'GENERATING')",id,documentId,u,v,d.getTitle()+" - Flashcards");Task task=tasks.createAndEnqueue(documentId,u,TaskType.GENERATE_FLASHCARDS);return Map.of("deckId",id,"taskId",task.getId(),"status","GENERATING","version",v);}
    public List<Map<String,Object>> decks(UUID id){UUID u=users.currentUserId();owned(id,u);return jdbc.queryForList("SELECT id,version,title,status,total_source_groups,completed_source_groups,quality_report_json,error_message,created_at FROM flashcard_decks WHERE document_id=? AND user_id=? ORDER BY version DESC",id,u);}
    public List<Map<String,Object>> cards(UUID id){UUID u=users.currentUserId();deck(id,u);return jdbc.queryForList("SELECT id,card_type,front,back,cloze_text,difficulty,topic,hint,tags_json,source_pages_json,confidence FROM flashcards WHERE deck_id=? ORDER BY source_group_index,item_index",id);}
    public List<Map<String,Object>> dueCards(UUID id,int limit){UUID u=users.currentUserId();deck(id,u);return jdbc.queryForList("SELECT f.id,f.card_type,f.front,f.back,f.cloze_text,f.difficulty,f.topic,f.hint,f.source_pages_json,COALESCE(s.status,'NEW') review_status,s.due_at FROM flashcards f LEFT JOIN flashcard_review_states s ON s.flashcard_id=f.id AND s.user_id=? WHERE f.deck_id=? AND (s.flashcard_id IS NULL OR (s.status<>'SUSPENDED' AND s.due_at<=NOW())) ORDER BY s.due_at NULLS FIRST,f.item_index LIMIT ?",u,id,Math.max(1,Math.min(limit,500)));}

    @Transactional public Map<String,Object> review(UUID cardId,String raw){UUID u=users.currentUserId();card(cardId,u);String grade=raw==null?"":raw.toUpperCase(Locale.ROOT);if(!GRADES.contains(grade))throw new IllegalArgumentException("Invalid review grade");var rows=jdbc.queryForList("SELECT status,ease_factor,interval_days,repetitions FROM flashcard_review_states WHERE user_id=? AND flashcard_id=?",u,cardId);String status="NEW";double ease=2.5;int interval=0,reps=0;if(!rows.isEmpty()){var r=rows.get(0);status=(String)r.get("status");ease=((Number)r.get("ease_factor")).doubleValue();interval=((Number)r.get("interval_days")).intValue();reps=((Number)r.get("repetitions")).intValue();}if("SUSPENDED".equals(status))throw new IllegalArgumentException("Card is suspended");int q=Map.of("AGAIN",1,"HARD",3,"GOOD",4,"EASY",5).get(grade);ease=Math.max(1.3,ease+(0.1-(5-q)*(0.08+(5-q)*0.02)));if("AGAIN".equals(grade)){reps=0;interval=1;status="LEARNING";}else{reps++;interval=reps==1?1:reps==2?6:Math.max(1,(int)Math.round(interval*ease));if("HARD".equals(grade))interval=Math.max(1,(int)Math.round(interval*.8));if("EASY".equals(grade))interval=Math.max(1,(int)Math.round(interval*1.3));status=reps>=2?"REVIEW":"LEARNING";}Instant now=Instant.now(),due=now.plus(interval,ChronoUnit.DAYS);jdbc.update("INSERT INTO flashcard_review_states(user_id,flashcard_id,status,ease_factor,interval_days,repetitions,due_at,last_reviewed_at,last_grade) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,flashcard_id) DO UPDATE SET status=EXCLUDED.status,ease_factor=EXCLUDED.ease_factor,interval_days=EXCLUDED.interval_days,repetitions=EXCLUDED.repetitions,due_at=EXCLUDED.due_at,last_reviewed_at=EXCLUDED.last_reviewed_at,last_grade=EXCLUDED.last_grade,updated_at=NOW()",u,cardId,status,ease,interval,reps,Timestamp.from(due),Timestamp.from(now),grade);return Map.of("status",status,"intervalDays",interval,"repetitions",reps,"dueAt",due,"grade",grade);}

    @Transactional public Map<String,Object> generateQuiz(UUID documentId){UUID u=users.currentUserId();Document d=ownedReady(documentId,u);var active=jdbc.queryForList("SELECT id,status FROM quiz_sets WHERE document_id=? AND user_id=? AND status IN ('GENERATING','PARTIAL') ORDER BY version DESC LIMIT 1",documentId,u);if(!active.isEmpty())return active.get(0);int v=jdbc.queryForObject("SELECT COALESCE(MAX(version),0)+1 FROM quiz_sets WHERE document_id=?",Integer.class,documentId);UUID id=UUID.randomUUID();jdbc.update("INSERT INTO quiz_sets(id,document_id,user_id,version,title,status,difficulty_distribution_json) VALUES (?,?,?,?,?,'GENERATING',?)",id,documentId,u,v,d.getTitle()+" - Quiz","{\"EASY\":0.3,\"MEDIUM\":0.5,\"HARD\":0.2}");Task task=tasks.createAndEnqueue(documentId,u,TaskType.GENERATE_QUIZ);return Map.of("quizSetId",id,"taskId",task.getId(),"status","GENERATING","version",v);}
    public List<Map<String,Object>> quizzes(UUID id){UUID u=users.currentUserId();owned(id,u);return jdbc.queryForList("SELECT id,version,title,status,total_source_groups,completed_source_groups,quality_report_json,error_message,created_at FROM quiz_sets WHERE document_id=? AND user_id=? ORDER BY version DESC",id,u);}
    public List<Map<String,Object>> questions(UUID id){UUID u=users.currentUserId();quiz(id,u);return jdbc.queryForList("SELECT id,question_type,difficulty,topic,stem,options_json,points,source_pages_json FROM quiz_questions WHERE quiz_set_id=? ORDER BY source_group_index,item_index",id);}
    @Transactional public Map<String,Object> startAttempt(UUID setId){UUID u=users.currentUserId();quiz(setId,u);UUID id=UUID.randomUUID();jdbc.update("INSERT INTO quiz_attempts(id,quiz_set_id,user_id,status) VALUES (?,?,?,'IN_PROGRESS')",id,setId,u);return Map.of("attemptId",id,"status","IN_PROGRESS");}
    @Transactional public Map<String,Object> saveAnswer(UUID attemptId,UUID questionId,String response){UUID u=users.currentUserId();attempt(attemptId,u,"IN_PROGRESS");int valid=jdbc.queryForObject("SELECT COUNT(*) FROM quiz_questions q JOIN quiz_attempts a ON a.quiz_set_id=q.quiz_set_id WHERE a.id=? AND q.id=?",Integer.class,attemptId,questionId);if(valid==0)throw new IllegalArgumentException("Question is not part of attempt");jdbc.update("INSERT INTO quiz_answers(id,attempt_id,question_id,user_response) VALUES (?,?,?,?) ON CONFLICT(attempt_id,question_id) DO UPDATE SET user_response=EXCLUDED.user_response,is_correct=NULL,awarded_points=NULL,feedback=NULL,key_points_hit_json=NULL,graded_by=NULL,updated_at=NOW()",UUID.randomUUID(),attemptId,questionId,response==null?"":response);return Map.of("saved",true);}
    @Transactional public Map<String,Object> submit(UUID attemptId){UUID u=users.currentUserId();attempt(attemptId,u,"IN_PROGRESS");UUID documentId=jdbc.queryForObject("SELECT s.document_id FROM quiz_attempts a JOIN quiz_sets s ON s.id=a.quiz_set_id WHERE a.id=?",UUID.class,attemptId);jdbc.update("INSERT INTO quiz_answers(id,attempt_id,question_id,user_response) SELECT gen_random_uuid(),?,q.id,'' FROM quiz_questions q JOIN quiz_attempts a ON a.quiz_set_id=q.quiz_set_id WHERE a.id=? ON CONFLICT(attempt_id,question_id) DO NOTHING",attemptId,attemptId);for(var r:jdbc.queryForList("SELECT a.id,q.correct_answer,a.user_response,q.points,q.explanation FROM quiz_answers a JOIN quiz_questions q ON q.id=a.question_id WHERE a.attempt_id=? AND q.question_type IN ('MULTIPLE_CHOICE','TRUE_FALSE')",attemptId)){boolean ok=norm((String)r.get("correct_answer")).equals(norm((String)r.get("user_response")));jdbc.update("UPDATE quiz_answers SET is_correct=?,awarded_points=?,feedback=?,key_points_hit_json='[]',graded_by='AUTO',updated_at=NOW() WHERE id=?",ok,ok?((Number)r.get("points")).doubleValue():0d,r.get("explanation"),r.get("id"));}int free=jdbc.queryForObject("SELECT COUNT(*) FROM quiz_answers a JOIN quiz_questions q ON q.id=a.question_id WHERE a.attempt_id=? AND q.question_type NOT IN ('MULTIPLE_CHOICE','TRUE_FALSE')",Integer.class,attemptId);if(free>0){jdbc.update("UPDATE quiz_attempts SET status='GRADING',submitted_at=NOW(),updated_at=NOW() WHERE id=?",attemptId);Task t=tasks.createAndEnqueue(documentId,u,TaskType.GRADE_QUIZ_ATTEMPT,attemptId);return Map.of("attemptId",attemptId,"taskId",t.getId(),"status","GRADING");}jdbc.update("UPDATE quiz_attempts a SET status='COMPLETED',score=x.score,max_score=x.maximum,submitted_at=NOW(),completed_at=NOW(),updated_at=NOW() FROM (SELECT COALESCE(SUM(ans.awarded_points),0) score,COALESCE(SUM(q.points),0) maximum FROM quiz_answers ans JOIN quiz_questions q ON q.id=ans.question_id WHERE ans.attempt_id=?) x WHERE a.id=?",attemptId,attemptId);return Map.of("attemptId",attemptId,"status","COMPLETED");}
    public Map<String,Object> attemptResult(UUID id){UUID u=users.currentUserId();attempt(id,u,null);Map<String,Object> meta=jdbc.queryForMap("SELECT id,quiz_set_id,status,score,max_score,weak_topics_json,started_at,submitted_at,completed_at FROM quiz_attempts WHERE id=?",id);var answers=jdbc.queryForList("SELECT ans.question_id,ans.user_response,ans.is_correct,ans.awarded_points,ans.feedback,ans.graded_by,q.stem,q.question_type,q.difficulty,q.topic,q.options_json,q.correct_answer,q.explanation,q.points FROM quiz_answers ans JOIN quiz_questions q ON q.id=ans.question_id WHERE ans.attempt_id=? ORDER BY q.source_group_index,q.item_index",id);return Map.of("attempt",meta,"answers",answers);}

    private String norm(String v){return v==null?"":v.trim().toUpperCase(Locale.ROOT);}private Document ownedReady(UUID id,UUID u){Document d=owned(id,u);if(d.getStatus()!=DocumentStatus.READY)throw new IllegalArgumentException("Document must be READY");return d;}private Document owned(UUID id,UUID u){return documents.findById(id).filter(d->d.getUserId().equals(u)).orElseThrow(()->new IllegalArgumentException("Document not found"));}private void deck(UUID id,UUID u){required("SELECT COUNT(*) FROM flashcard_decks WHERE id=? AND user_id=?",id,u,"Deck not found");}private void card(UUID id,UUID u){required("SELECT COUNT(*) FROM flashcards f JOIN flashcard_decks d ON d.id=f.deck_id WHERE f.id=? AND d.user_id=?",id,u,"Card not found");}private void quiz(UUID id,UUID u){required("SELECT COUNT(*) FROM quiz_sets WHERE id=? AND user_id=? AND status='READY'",id,u,"Quiz not ready");}private void attempt(UUID id,UUID u,String status){String sql="SELECT COUNT(*) FROM quiz_attempts WHERE id=? AND user_id=?"+(status==null?"":" AND status='"+status+"'");required(sql,id,u,"Attempt not found or invalid state");}private void required(String sql,UUID id,UUID u,String msg){Integer n=jdbc.queryForObject(sql,Integer.class,id,u);if(n==null||n==0)throw new IllegalArgumentException(msg);}
}
