package com.noteflow.tasks;

public enum TaskStep {
    UPLOADED,
    PARSING_PDF,
    EXTRACTING_TEXT,
    ANALYZING_VISUAL_CONTENT,
    CROPPING_VISUAL_REGIONS,
    VLM_ANALYSIS,
    LAYOUT_CHUNKING,
    CHUNKING,
    GENERATING_EMBEDDINGS,
    GENERATING_NOTES,
    COMPLETED,
    FAILED
}
