package com.noteflow.tasks;

public enum TaskType {
    PARSE_DOCUMENT,
    GENERATE_EMBEDDINGS,
    GENERATE_NOTES,
    GENERATE_FLASHCARDS,
    GENERATE_QUIZ,
    GRADE_QUIZ_ATTEMPT,
    ASK_DOCUMENT,
    EXPORT_MARKDOWN
}
